apiVersion: apps/v1
kind: Deployment
metadata:
  name: p1
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: p1
          image: mrmukesh77/artifact:1.0
          ports:
          - containerPort: 8080
